baseurl: /
languageCode: en-us
title: "Turtletopia: a blog about programming in R"
theme: hugo-lithium
googleAnalytics: 'G-2SKRPRGMM0'
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
relativeURLs: true
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/turtletopia
    - name: Twitter
      url: https://twitter.com/Rturtletopia
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: We’ve studied and worked together on several R projects in many domains over the last few years. There were shiny apps, machine learning, bioinformatics, Rcpp, data visualization… we can’t even list it all. And the time has come to share that knowledge.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  customCSS: ["css/custom.css"]
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  categoryColors:
    Overview: "#D33F49B0"
    Tutorial: "#77BA99B0"
    Organisational: "#D7C0D0B0"
    Essay: "#FABC2AB0"
    Turtletools: "#52489CB0"
    Default: "#EEEEEEB0"
  images:
    - images/logo.png
  relativeURLs: true
  address: https://turtletopia.github.io
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
privacy:
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false
